# framework specific different locations

## Report ####
logs=Reports/System Logs/
deviceLog=Reports/Mobile Device Logs/
report=Reports/Test Execution Reports/
reportCss=Reports/Report/report.css
recording=Reports/Test Execution Reports/Test Videos/
reportfailedXMl=Reports/Report/TestNGfailedxml/
MainReport=Reports/Report/Main
RetryReport=Reports/Report/Retry
reportColumn=strStepDesc,strExpResult,strActualResult,strStatus

## ScreenShot Folder
Screenshot=Reports/Report/Screenshot/

## Browser EXE
Driver=./src/Resources/Drivers/

## Object repository ./src/test/resources/OR/
objectrepository =Object Manager/OR/

## TestNG XML File
TestNG=Test Suite/TestNG Suite/
testsuite =Test Suite/Excel Suite/
testdata =./src/dataEngine/DataFiles/
config=./src/dataEngine/DataFiles/

## Template file folder
templatedir=./src/Resources/Templates/
tempreportdir=test-output/html/
RetryFailedXML=test-output/html/TestNGfailedxml/
implicitWait=5

## ADB locator
adblocation=/Users/himanshug/Android_SDK/platform-tools/adb

## Mobile App location
apploc=Data/MobileApp/

## Browser Setting
FileDownloadPath=/Data/DownloadedData/

FileTypeToBeDownload=application/pdf

### Appium ####
AppiumLog=Appium.log
browserInstance=1

### switch Automation Dashboard Report #### options are yes/no
enableMongoDashBoard=no
mongoDbLocation=mongodb://kamleshk:Pyramid1234@ds259897.mlab.com:59897/report 
##mongoDbLocation=mongodb://localhost:27017/report

######Zip Report HTML Name#### xrayJsonWebToken options are yes/no
zipFileScreenshots=No
htmlZipReportName=AutomationExecutionResult.zip

####Xray Template Name######
xRayTestsResultWithIndividualReport=Xray/xRayTestsResult.tmpl
xRayTestsWithIndividualReport=Xray/xRayTests.tmpl
xRayTestsResultWithoutIndividualReport=Xray/xRayTestsResultWithoutIndividualReport.tmpl
xRayTestsWithoutIndividualReport=Xray/xRayTestsWithoutIndividualReport.tmpl

### switch Automation Dashboard Report #### options are yes/no
enableDashBoard=no
mySQLConnString=10.4.3.188:3306/dashboard
mySQLConnUserName=dbadmin
mySQLConnPassword=Pyramid@123
##mongoDbLocation=mongodb://localhost:27017/report






